#!/bin/sh

ID="`xinput list | grep -Eio '(touchpad|glidepoint)\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`"
STATE="`xinput list-props $ID | grep 'Device Enabled' | awk '{print $4}'`"

{ [ $STATE -eq 1 ] && xinput disable $ID; } ||
{ xinput enable $ID; }
